unbind r

set -g mouse on
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s

# so that neovim can tell when go in and out of it
set -g focus-events on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# window-split binds
unbind '"' # default bind for split-window -v
unbind % # default bind for split-window -h
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# gets rid of the confirm-before for killing panes
bind-key x kill-pane

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
