# general
set -g mouse on
set -g prefix C-s
unbind r
bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1
setw -g pane-base-index 1

# navigation binds
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# window-split binds
unbind '"' # default bind for split-window -v
unbind % # default bind for split-window -h
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# gets rid of the confirm-before for killing panes
bind-key x kill-pane

# mini status bar
set -g status-style "bg=black,fg=white"
set -g status-left "#[fg=white] #S │ "
set -g status-left-length 50
set -g status-right ""
# status-bar messages
set -g message-style "bg=#000000,fg=white,bold"
set -g message-command-style "bg=#262626,fg=white"

# window styles
set -g window-status-style "bg=default,fg=#666666"
set -g window-status-format "#I:#W"
set -g window-status-current-style "bg=default,fg=white,bold"
set -g window-status-current-format "#I:#W"
set -g window-status-separator " "

# pane styles
set -g pane-active-border-style "bg=default,fg=white"
set -g pane-border-style "bg=default,fg=#303030"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# for auto-save sessions
set -g @continuum-restore 'on'

# so that neovim can tell when go in and out of it, this gets fed into vim.autoread
set -g focus-events on

# run tpm
run '~/.tmux/plugins/tpm/tpm'
