# general
set -g mouse on
set -g prefix C-s
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# navigation binds
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# window-split binds
unbind '"' # default bind for split-window -v
unbind % # default bind for split-window -h
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# gets rid of the confirm-before for killing panes
bind-key x kill-pane

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# for auto-save sessions
set -g @continuum-restore 'on'

# so that neovim can tell when go in and out of it, this gets fed into vim.autoread
set -g focus-events on

# run tpm
run '~/.tmux/plugins/tpm/tpm'
