monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*Beluga*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "iec958-stereo"
      }
    }
  }
]
